name: kind-action
on:
  pull_request:
  push:
    paths:
      - 'kind-action/**'
env:
  go-version: "1.20"
jobs:
  kind:
    name: Kind Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - name: Setup kind cluster
        uses: helm/kind-action@v1.5.0
        with:
          version: "v0.20.0"
          config: "kind-action/manifests/kind-k8sdev-no-cni.yaml"
      - name: Check kind cluster
        run: |
          ls -lat /
          which kind || true
          which kubectl || true
          kind get clusters || true
          kubectl cluster-info --context kind-k8sdev || true
          kubectl config get-contexts || true
          kubectl --context k8sdev get nodes || true
